"""数据库修改

Revision ID: 0c8e0469842d
Revises: a69eb2597e7c
Create Date: 2025-11-28 16:11:33.574234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c8e0469842d'
down_revision: Union[str, Sequence[str], None] = 'a69eb2597e7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversation_member',
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('chat_conversation_conversation_key_key'), 'chat_conversation', type_='unique')
    op.drop_column('chat_conversation', 'conversation_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversation', sa.Column('conversation_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('chat_conversation_conversation_key_key'), 'chat_conversation', ['conversation_key'], postgresql_nulls_not_distinct=False)
    op.drop_table('chat_conversation_member')
    # ### end Alembic commands ###
