"""add user login record

Revision ID: 597ec40d007b
Revises: a8f4403243e6
Create Date: 2025-11-13 17:30:04.967548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '597ec40d007b'
down_revision: Union[str, Sequence[str], None] = 'a8f4403243e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_login_log',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('ip_addr', sa.String(length=39), nullable=True),
    sa.Column('login_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('t_user_account')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_user_account',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['t_user.id'], name=op.f('t_user_account_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('t_user_account_pkey')),
    sa.UniqueConstraint('email', name=op.f('t_user_account_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('user_login_log')
    op.drop_table('user_account')
    # ### end Alembic commands ###
