"""增加base

Revision ID: d53553d2efe6
Revises: 1fb392417ca9
Create Date: 2025-11-12 20:09:34.929441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd53553d2efe6'
down_revision: Union[str, Sequence[str], None] = '1fb392417ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('t_user', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('t_user', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('t_user', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('t_user', 'updated_at')
    op.drop_column('t_user', 'created_at')
    # ### end Alembic commands ###
